base:
  net_maxpacketdrop: 0
  cl_timeout: 60
  sv_lan: 1
  net_maxcleartime: 0
  net_maxfilesize: 64
  mat_parallaxmap: 0
  mat_software_aa_strength: 0
  mat_software_aa_strength_vgui: 0
  mat_viewportscale: 1
  mat_vsync: 0
  engine_no_focus_sleep: 50
  r_occludeemaxarea: 1
  r_occluderminarea: 1
  r_occludermincount: 2
  r_norefresh: 1
  fast_fogvolume: 1
  mod_offline_hdr_switch: 1
  mat_forcemanagedtextureintohardware: 0
  r_hunkalloclightmaps: 0
  r_lightcache_zbuffercache: 1
  mat_requires_rt_alloc_first: 0
  sys_minidumpspewlines: 0
  mp_usehwmmodels: -1
  gl_pow2_tempmem: 1
  mat_texture_reload_frame_swap_workaround: 0
  gl_mtglflush_at_tof: 1
  gl_debug_output: 0
  gl_magnify_resolve_mode: 1
  gl_batch_tex_creates: 1
  gl_batch_tex_destroys: 1
  gl_radar7954721_workaround_mixed: 0
  gl_amd_occlusion_workaround: 0
  gl_paircache_rows_lg2: 14
  sv_motd_unload_on_dismissal: 1
  fov_desired: 90
  bugreporter_uploadasync: 1
  lzma_persistent_buffer: 1
  mat_bufferprimitives: 1
  filesystem_buffer_size: 1
  filesystem_max_stdio_read: 64
  snd_async_fullyasync: 0
  snd_async_minsize: 262144
  snd_mixahead: .066
  snd_noextraupdate: 1
  snd_async_spew_blocking: 0
sp:
  cl_interp: .1
  cl_interp_ratio: 5
mp:
  cl_smoothtime: .015
  net_chokeloop: 1
  cl_localnetworkbackdoor: 0
no_flashlight:
  r_flashlighdepthtexture: 0
  r_flashlightrender: 0
  r_flashlightmodels: 0
  r_flashlightculldepth: 0
  r_flashlightscissor: 0
tf:
  hud_escort_interp: .1
  tf_hud_num_building_alert_beeps: 2
  tf_hud_show_servertimelimit: 1
  tf_hud_target_id_alpha: 100
  hud_medichealtargetmarker: 1
  tf_hud_target_id_show_avatars: 2
tf2:
  tf_mm_debug_level: 0
  tf_party_join_request_mode: 1
  tf_dashboard_slide_time: .1
  tf_item_inspect_model_auto_spin: 1
  tf_item_inspect_model_spin_rate: 30
  tf_colorblindassist: 1
  tf_scoreboard_ping_as_text: 1
  cl_mute_all_comms: 1
  tf_chat_popup_hold_time: 2.5
  tf_time_loading_item_panels: .0004
  tf_backpack_page_button_delay: .25
  cl_notifications_move_time: .1
  cl_mvm_wave_status_visible_during_wave: 1
  cl_use_tournament_specgui: 1
  cl_always_flush_models: 0
  tf_dingalingaling_repeat_delay: .008
